# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
-   repo: https://github.com/hhatto/autopep8
    rev: v2.0.4
    hooks:
    -   id: autopep8
-   repo: https://github.com/pylint-dev/pylint
    rev: v3.0.2
    hooks:
    -   id: pylint
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.5
    hooks:
    -   id: clang-format
exclude: "^submodules/"
